[package]
name = "feg"
version = "0.1.0"
authors = ["chrisf"]

[dependencies]
ggez = { git = "https://github.com/ggez/ggez.git", branch = "master" }
num = "*"

[dev-dependencies]
indoc = "*"
maplit = "*"
